[package]
name = "rodioplay"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
rodio = "0.8"

[patch.crates-io]
cpal = { git = "https://gitlab.redox-os.org/redox-os/cpal.git", branch = "redox" }
